name: Subir Imagenes a DockerHub

on:
  push:
    branches: [ "main" ]

jobs:
  construir-y-subir:
    runs-on: ubuntu-latest
    steps:
    - name: 1. Descargar el código
      uses: actions/checkout@v3

    - name: 2. Iniciar sesión en DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: 3. Construir y subir BACKEND
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-examen:latest ./backend
        docker push ${{ secrets.DOCKER_USERNAME }}/backend-examen:latest

    - name: 4. Construir y subir FRONTEND
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-examen:latest ./frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend-examen:latest